apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffusion-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diffusion-api
  template:
    metadata:
      labels:
        app: diffusion-api
    spec:
      containers:
      - name: diffusion-api
        image: your-dockerhub-username/diffusion-api:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
